name: Daily Commit

on:
  schedule:
    # Runs every day at 18:00 UTC
    - cron: '0 18 * * *'
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: üîç Check out code
      uses: actions/checkout@v2

    - name: ‚ö°Ô∏è Update README
      run: |
        echo "Making daily contribution"
        echo "<br />- $(date)" >> README.md
    - name: ‚úÖ Commit & Push
      run: |
        git config --local user.email "ramin.rezaei77@gmail.com"
        git config --local user.name "Ramin"
        git remote set-url origin https://$GITHUB_TOKEN@github.com/raminr77/ramin-zone.git
        git add README.md
        git commit -m "New Emoji Added $RANDOM_EMOJI"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
